#!/bin/sh

### BEGIN INIT INFO
# Provides:       makelight
# Default-Start:  5
# Default-Stop:
# Required-Start: networking
# Required-Stop:
### END INIT INFO

case "$1" in
	start)
		while [ "`ip addr show scope global | wc -l`" -eq "0" ]
		do
			sleep 5
		done
		sudo -ulight ~light/server ~light/light &
		;;
	stop)
		sudo -ulight killall tail
		;;
	restart)
		"$0" stop && "$0" start
		;;
	*)
		echo "Unsupported!" >&2
		exit 1
esac

true
