#!/bin/sh

readonly SOCKDIR="/tmp/lightsocket"
readonly SOCKET="$SOCKDIR/socket"
readonly OUT="$SOCKDIR/out"
readonly ERR="$SOCKDIR/err"

cmd="./light"
if [ "$#" -gt 0 ]
then
	cmd="$@"
fi

mkdir -p "$SOCKDIR"

rm -f "$SOCKET"
mkfifo "$SOCKET"
chmod g+w "$SOCKET"

truncate -s0 "$OUT" "$ERR"
chmod g+w "$OUT" "$ERR"

"$cmd" <"$SOCKET" >"$OUT" 2>"$ERR" &
tail -f >"$SOCKET"
